
<!DOCTYPE html>
<html lang="en">

<head> <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ env('APP_NAME') }}">
    <meta name="keywords" content="">
    <meta name="author" content="Benue Digital Infrastructure Company">


    <!-- Favicon icon-->
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('images/favicon.ico') }}">

    <!-- Libs CSS -->
    <link href="{{ asset('tfa/fonts/feather/feather.css') }}" rel="stylesheet">
    <link href="{{ asset('tfa/libs/bootstrap-icons/font/bootstrap-icons.css') }}" rel="stylesheet" />
    <link href="{{ asset('tfa/libs/mdi/font/css/materialdesignicons.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('tfa/libs/simplebar/dist/simplebar.min.css') }}" rel="stylesheet">
    <!-- Theme CSS -->
    <link rel="stylesheet" href="{{ asset('tfa/css/theme.min.css') }}">
    <title>{{ env('APP_NAME') }} | Login</title>


    <style type="text/css">
        .password-toggle {
            position: relative;
        }

        .password-toggle input[type="password"] {
            padding-right: 30px;
        }

        .password-toggle .toggle-password {
            position: absolute;
            top: 72%;
            right: 20px;
            transform: translateY(-50%);
            cursor: pointer;
        }

        [data-theme="dark"] ::placeholder {
            color: white;
        }
    </style>
</head>

<body>
    <!-- Page content -->
    <main>
        <section class="container d-flex flex-column">
            <div class="row align-items-center justify-content-center g-0 min-vh-100">

                <div class="col-lg-5 col-md-8 py-8 py-xl-0">
                    <!-- Card -->
                    <div class="card shadow ">
                        <!-- Card body -->
                        <div class="card-body p-6">
                            <div class="mb-4 row">
                                <div class="col-12 text-center">
                                    <a href="/"><img src="{{ asset('assets/logo.png') }}" class="mb-4"
                                            alt="" style="height: 50px"></a>
                                </div>
                                <div class="col-12">
                                    <h2 class="mb-1 fw-bold text-center">2FA Authentication</h2>
                                </div>
                            </div>
                            <p style="color: black">Hello
                                <strong>{{ Auth::user()->first_name . ' ' . Auth::user()->surname }}</strong>,
                                <br>Enter the verification code generated by your mobile application (Google
                                Authenticator).
                            </p>
                            <!-- Form -->
                            <form method="POST" action="{{ route('login.2fa') }}" class="mt-4 login-form">
                                @csrf
                                <div class="row">

                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label><strong>Google Authentication Code</strong> <span
                                                    class="text-danger">*</span></label>
                                            <div class="position-relative">
                                                <i data-feather="key" class="fea icon-sm icons"></i>
                                                <input type="text"
                                                    class="pl-5 form-control{{ $errors->has('google2fa_code') ? ' is-invalid' : '' }}"
                                                    name="google2fa_code" value="{{ old('google2fa_code') }}"
                                                    value="" id="gacode"
                                                    placeholder="Enter Google Authentication Code" required>

                                                @if (Session::has('error'))
                                                    <span class="" role="alert" style="color:red; font-size:14px">
                                                        <strong>Invalid Google Authenticator 2FA Code.</strong>
                                                    </span>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    <!--end col-->

                                    <!--end col-->
                                    <div class="mb-0 col-12 mt-4">
                                        <button class="btn btn-success btn-block"
                                            type="submit" style="width: 100% !important">Authenticate</button>
                                    </div>
                                    <p class="p-3 text-danger">
                                        If you lost your phone or uninstalled the Google Authenticator app and
                                        unable to access your account please contact us.
                                    </p>
                                    <!--end col-->

                                    <div class="text-center col-12">
                                        <p class="mt-4 mb-0"><small class="mr-2 text-dark" style="font-weight: bold">&copy; Copyright
                                                {{ date('Y') }} &nbsp; {{ env('APP_NAME') }} <br />
                                                All Rights Reserved.</small>
                                        </p>
                                    </div>
                                </div>
                                <!--end row-->
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <!-- Scripts -->
    <!-- Libs JS -->
    <script src="{{ asset('tfa/libs/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('tfa/libs/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('tfa/libs/simplebar/dist/simplebar.min.js') }}"></script>

    <!-- Theme JS -->
    <script src="{{ asset('tfa/js/theme.min.js') }}"></script>
    @include('sweetalert::alert')
    <script src="{{ asset('tfa/js/vendors/sweetalert2.all.min.js') }}"></script>




</body>

</html>

